# Generated by Django 3.2 on 2021-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hannoi_lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('Four', models.CharField(max_length=20)),
                ('Three', models.CharField(max_length=20)),
                ('Two', models.CharField(max_length=20)),
            ],
        ),
    ]
