# Generated by Django 3.2 on 2021-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanoi_lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hannoi_special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('Four', models.CharField(max_length=20)),
                ('Three', models.CharField(max_length=20)),
                ('Two', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hannoi_vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('Four', models.CharField(max_length=20)),
                ('Three', models.CharField(max_length=20)),
                ('Two', models.CharField(max_length=20)),
            ],
        ),
    ]
